[package]
name = "netcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
pnet = "0.35.0"
ratatui = "0.26.3"
resolv-conf = "0.7.0"
rustdns = "0.4.0"
